---
- name: Auditoria de usuários Linux/AIX
  hosts: servidores
  gather_facts: no
  vars_files:
    - user.txt

  tasks:

    - name: Criar diretório base de resultados
      delegate_to: localhost
      file:
        path: "resultados/{{ inc }}"
        state: directory

    - name: Coletar data atual do host
      command: date "+%Y-%m-%d %H:%M:%S"
      register: date_output

    - name: Verificar usuario_ldap
      shell: "id {{ user }}"
      register: usuario_ldap
      ignore_errors: yes

    - name: Registrar resultado usuario_ldap
      delegate_to: localhost
      copy:
        content: "{{ inventory_hostname }} | {{ date_output.stdout }} | {{ usuario_ldap.stdout }}"
        dest: "resultados/{{ inc }}/usuario_ldap"
        mode: '0644'
      when: usuario_ldap.rc == 0

    - name: Verificar usuario_local
      shell: "grep -i {{ user }} /etc/passwd"
      register: usuario_local
      ignore_errors: yes

    - name: Registrar resultado usuario_local
      delegate_to: localhost
      copy:
        content: "{{ inventory_hostname }} | {{ date_output.stdout }} | {{ usuario_local.stdout }}"
        dest: "resultados/{{ inc }}/usuario_local"
        mode: '0644'
      when: usuario_local.rc == 0

    - name: Verificar presente_group
      shell: "grep -i {{ user }} /etc/group"
      register: presente_group
      ignore_errors: yes

    - name: Registrar resultado presente_group
      delegate_to: localhost
      copy:
        content: "{{ inventory_hostname }} | {{ date_output.stdout }} | {{ presente_group.stdout }}"
        dest: "resultados/{{ inc }}/presente_group"
        mode: '0644'
      when: presente_group.rc == 0

    - name: Verificar privilegio_sudoers
      shell: "grep -i {{ user }} /etc/sudoers"
      register: privilegio_sudoers
      ignore_errors: yes

    - name: Registrar resultado privilegio_sudoers
      delegate_to: localhost
      copy:
        content: "{{ inventory_hostname }} | {{ date_output.stdout }} | {{ privilegio_sudoers.stdout }}"
        dest: "resultados/{{ inc }}/privilegio_sudoers"
        mode: '0644'
      when: privilegio_sudoers.rc == 0

    - name: Registrar resultado remocao_ok
      delegate_to: localhost
      copy:
        content: "{{ inventory_hostname }} | {{ date_output.stdout }} | Nenhum item encontrado"
        dest: "resultados/{{ inc }}/remocao_ok"
        mode: '0644'
      when:
        - usuario_ldap.rc != 0
        - usuario_local.rc != 0
        - presente_group.rc != 0
        - privilegio_sudoers.rc != 0
 
